### PR TITLE
Add very simple test for version argument and use importlib feature instead of deprecated pkg_resources for version

### PR DESCRIPTION
**Pull request by white-gecko**
Add very simple test for version argument and use importlib feature instead of deprecated pkg_resources for version.

Drop python 3.7 support (importlib.metadata) was introduced with python 3.8

Derived from https://github.com/webrecorder/warcio/pull/169 . Lets split it into portions.

### CODE REVIEW

**Comment by wumpus** [comment]
@tw4l should we care about Py 3.7? It was end of life last summer.

**Comment by wumpus** [comment]
@white-gecko would you mind adding 3.7 support by checking for ImportError? We have some examples of that elsewhere in this package, for example brotli support in warcio/bufferedreader.py

**Comment by white-gecko** [comment]
Sure I could add it but thought, maybe its not worth it, if 3.7 could be droped all over. I will look into it on Monday.

**Comment by white-gecko** [comment]
> @white-gecko would you mind adding 3.7 support by checking for ImportError? We have some examples of that elsewhere in this package, for example brotli support in warcio/bufferedreader.py

I have added the requested change.

**Comment by wumpus** [comment]
Thank you. The method to this madness is that this package is used in a lot of libraries by users on older python versions. Historically we've tried to make small adjustments to keep older versions still running.

At this point we can add py3.12 to the CI tests, and I've already verified that it and py3.13.0-rc.0 pass.

**Pull request merged**
