### PR TITLE
Handle deprecation of naive datetime functions like utcnow()

### LINKED ISSUE #163: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version
Since Python 3.12, we have the following DeprecationWarning:

```
warcio/recordbuilder.py:156: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
    return datetime_to_iso_date(datetime.datetime.utcnow(), use_micros=use_micros)
```

Pretty easy to fix in 3.12, but maybe not that easy in reality since you probably wanna maintain 2.7+ and 3.4+ support. I suggest to not use what the DeprecationWarning suggests but `datetime.datetime.now(tzinfo = datetime.tzinfo.UTC)` which should be OK (to be checked).

### PR DESCRIPTION
**Pull request by tw4l**
Fixes #163 

The approach taken follows the advice in https://github.com/webrecorder/warcio/issues/163#issuecomment-2313410986 of returning naive datetimes by default, but (and this is a little different than suggested) allowing callers to specify `tz_aware=True` to receive an aware datetime with `tzinfo=datetime.timezone.utc`. This should prevent comparison errors between naive and aware datetimes for now while giving us a clear path forward if and when naive datetimes are fully deprecated in a future Python version.

### CODE REVIEW

**Comment by tw4l** [comment]
Oops, missed a few calls, putting back to draft for now

**Comment by wumpus** [comment]
Doesn't the WARC standard require utc? From looking at my crawler-that-uses-warcio I appear to have forced everything to UTC already, but then again my side-gig is astronomy.

**Comment by tw4l** [comment]
> Doesn't the WARC standard require utc? From looking at my crawler-that-uses-warcio I appear to have forced everything to UTC already, but then again my side-gig is astronomy.

Hi Greg, the question here is less about UTC vs other timezones and more about Python's naive vs aware datetime times. Miguel Grinberg has a pretty good blog post about how exactly this issue came about: https://blog.miguelgrinberg.com/post/it-s-time-for-a-change-datetime-utcnow-is-now-deprecated

With this PR, by default naive datetimes representing UTC will continue to be used, or for a UTC aware timezone a user can pass in `datetime.timezone.utc` as an argument to the methods. I suppose we could simply make the flag `aware` or similar to ensure that UTC is always being used if a timezone is specified.

**Review by ikreymer — APPROVED** [review]

**Comment by tw4l** [comment]
@ikreymer @wumpus Since Greg had a good point that the WARC spec always expects UTC, I changed the `tzinfo` argument on the time utility functions to an `aware` bool defaulting to False. If set to true, the returned datetime will be timezone-aware with `tzinfo=datetime.timezone.utc`

**Pull request merged**
